# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "JSONStream-0.10.0" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-0.10.0.tgz";
        sha1 = "74349d0d89522b71f30f0a03ff9bd20ca6f12ac0";
      };
    };
    "JSONStream-1.3.5" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.5.tgz";
        sha512 = "E+iruNOY8VV9s4JEbe1aNEm6MiszPRr/UfcHMz0TQh1BXSxHK+ASV1R6W4HpjBhSeS+54PIsAMCBmwD06LLsqQ==";
      };
    };
    "acorn-7.3.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.3.1.tgz";
        sha512 = "tLc0wSnatxAQHVHUapaHdz72pi9KUyHjq5KyHjGg9Y8Ifdc79pTh2XvI6I1/chZbnM7QtNKzh66ooDogPZSleA==";
      };
    };
    "acorn-node-1.8.2" = {
      name = "acorn-node";
      packageName = "acorn-node";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-node/-/acorn-node-1.8.2.tgz";
        sha512 = "8mt+fslDufLYntIoPAaIMUe/lrbrehIiwmR3t2k9LljIzoigEPF27eLk2hy8zSGzmR/ogr7zbRKINMo1u0yh5A==";
      };
    };
    "acorn-walk-7.2.0" = {
      name = "acorn-walk";
      packageName = "acorn-walk";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-walk/-/acorn-walk-7.2.0.tgz";
        sha512 = "OPdCF6GsMIP+Az+aWfAAOEt2/+iVDKE7oy6lJ098aoe59oAmK76qV6Gw60SbZ8jHuG2wH058GF4pLFbYamYrVA==";
      };
    };
    "asn1.js-4.10.1" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-4.10.1.tgz";
        sha512 = "p32cOF5q0Zqs9uBiONKYLm6BClCoBCM5O9JfeUSlnQLBTxYdTK+pW+nXflm8UkKd2UYlEbYz5qEi0JuZR9ckSw==";
      };
    };
    "assert-1.5.0" = {
      name = "assert";
      packageName = "assert";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.5.0.tgz";
        sha512 = "EDsgawzwoun2CZkCgtxJbv392v4nbk9XDD06zI+kQYoBM/3RBWLlEyJARDOmhAAosBjWACEkKL6S+lIZtcAubA==";
      };
    };
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-1.3.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz";
        sha512 = "mLQ4i2QO1ytvGWFWmcngKO//JXAQueZvwEKtjgQFM4jIK0kU+ytMfplL8j+n5mspOfjHwoAg+9yhb7BwAHm36g==";
      };
    };
    "bn.js-4.11.9" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.11.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.11.9.tgz";
        sha512 = "E6QoYqCKZfgatHTdHzs1RRKP7ip4vvm+EyRUeE2RF0NblwVvb0p6jSVeNTOFxPn26QXN2o6SMfNxKp6kU8zQaw==";
      };
    };
    "bn.js-5.1.2" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-5.1.2.tgz";
        sha512 = "40rZaf3bUNKTVYu9sIeeEGOg7g14Yvnj9kH7b50EiwX0Q7A6umbvfI5tvHaOERH0XigqKkfLkFQxzb4e6CIXnA==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "brorand-1.1.0" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.1.0.tgz";
        sha1 = "12c25efe40a45e3c323eb8675a0a0ce57b22371f";
      };
    };
    "browser-pack-6.1.0" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-pack/-/browser-pack-6.1.0.tgz";
        sha512 = "erYug8XoqzU3IfcU8fUgyHqyOXqIE4tUTTQ+7mqUjQlvnXkOO6OlT9c/ZoJVHYoAaqGxr09CN53G7XIsO4KtWA==";
      };
    };
    "browser-resolve-1.11.3" = {
      name = "browser-resolve";
      packageName = "browser-resolve";
      version = "1.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-resolve/-/browser-resolve-1.11.3.tgz";
        sha512 = "exDi1BYWB/6raKHmDTCicQfTkqwN5fioMFV4j8BsfMU4R2DK/QfZfK7kOVkmWCNANf0snkBzqGqAJBao9gZMdQ==";
      };
    };
    "browserify-16.5.1" = {
      name = "browserify";
      packageName = "browserify";
      version = "16.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify/-/browserify-16.5.1.tgz";
        sha512 = "EQX0h59Pp+0GtSRb5rL6OTfrttlzv+uyaUVlK6GX3w11SQ0jKPKyjC/54RhPR2ib2KmfcELM06e8FxcI5XNU2A==";
      };
    };
    "browserify-aes-1.2.0" = {
      name = "browserify-aes";
      packageName = "browserify-aes";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-aes/-/browserify-aes-1.2.0.tgz";
        sha512 = "+7CHXqGuspUn/Sl5aO7Ea0xWGAtETPXNSAjHo48JfLdPWcMng33Xe4znFvQweqc/uzk5zSOI3H52CYnjCfb5hA==";
      };
    };
    "browserify-cache-api-3.0.1" = {
      name = "browserify-cache-api";
      packageName = "browserify-cache-api";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-cache-api/-/browserify-cache-api-3.0.1.tgz";
        sha1 = "96247e853f068fd6e0d45cc73f0bb2cd9778ef02";
      };
    };
    "browserify-cipher-1.0.1" = {
      name = "browserify-cipher";
      packageName = "browserify-cipher";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-cipher/-/browserify-cipher-1.0.1.tgz";
        sha512 = "sPhkz0ARKbf4rRQt2hTpAHqn47X3llLkUGn+xEJzLjwY8LRs2p0v7ljvI5EyoRO/mexrNunNECisZs+gw2zz1w==";
      };
    };
    "browserify-des-1.0.2" = {
      name = "browserify-des";
      packageName = "browserify-des";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-des/-/browserify-des-1.0.2.tgz";
        sha512 = "BioO1xf3hFwz4kc6iBhI3ieDFompMhrMlnDFC4/0/vd5MokpuAc3R+LYbwTA9A5Yc9pq9UYPqffKpW2ObuwX5A==";
      };
    };
    "browserify-incremental-3.1.1" = {
      name = "browserify-incremental";
      packageName = "browserify-incremental";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-incremental/-/browserify-incremental-3.1.1.tgz";
        sha1 = "0713cb7587247a632a9f08cf1bd169b878b62a8a";
      };
    };
    "browserify-rsa-4.0.1" = {
      name = "browserify-rsa";
      packageName = "browserify-rsa";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-rsa/-/browserify-rsa-4.0.1.tgz";
        sha1 = "21e0abfaf6f2029cf2fafb133567a701d4135524";
      };
    };
    "browserify-sign-4.2.0" = {
      name = "browserify-sign";
      packageName = "browserify-sign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-sign/-/browserify-sign-4.2.0.tgz";
        sha512 = "hEZC1KEeYuoHRqhGhTy6gWrpJA3ZDjFWv0DE61643ZnOXAKJb3u7yWcrU0mMc9SwAqK1n7myPGndkp0dFG7NFA==";
      };
    };
    "browserify-zlib-0.2.0" = {
      name = "browserify-zlib";
      packageName = "browserify-zlib";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.2.0.tgz";
        sha512 = "Z942RysHXmJrhqk88FmKBVq/v5tqmSkDz7p54G/MGyjMnCFFnC79XWNbg+Vta8W6Wb2qtSZTSxIGkJrRpCFEiA==";
      };
    };
    "buffer-5.2.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.2.1.tgz";
        sha512 = "c+Ko0loDaFfuPWiL02ls9Xd3GO3cPVmUobQ6t3rXNUk304u6hGq+8N/kFi+QEIKhzK3uwolVhLzszmfLmMLnqg==";
      };
    };
    "buffer-crc32-0.2.13" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz";
        sha1 = "0d333e3f00eac50aa1454abd30ef8c2a5d9a7242";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "buffer-xor-1.0.3" = {
      name = "buffer-xor";
      packageName = "buffer-xor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz";
        sha1 = "26e61ed1422fb70dd42e6e36729ed51d855fe8d9";
      };
    };
    "builtin-status-codes-3.0.0" = {
      name = "builtin-status-codes";
      packageName = "builtin-status-codes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-status-codes/-/builtin-status-codes-3.0.0.tgz";
        sha1 = "85982878e21b98e1c66425e03d0174788f569ee8";
      };
    };
    "cached-path-relative-1.0.2" = {
      name = "cached-path-relative";
      packageName = "cached-path-relative";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cached-path-relative/-/cached-path-relative-1.0.2.tgz";
        sha512 = "5r2GqsoEb4qMTTN9J+WzXfjov+hjxT+j3u5K+kIVNIwAd99DLCJE9pBIMP1qVeybV6JiijL385Oz0DcYxfbOIg==";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "Kkht5ye6ZGmwv40uUDZztayT2ThLQGfnj/T71N/XzeZeo3nf8foyW7zGTsPYkEya3m5f3cAypH+qe7YOrM1U2Q==";
      };
    };
    "colors-1.4.0" = {
      name = "colors";
      packageName = "colors";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.4.0.tgz";
        sha512 = "a+UqTh4kgZg/SlGvfbzDHpgRu7AAQOmmqRHJnxhRZICKFUT91brVhNNt58CMWU9PsBbv3PDCZUHbVxuDiH2mtA==";
      };
    };
    "combine-source-map-0.8.0" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.8.0.tgz";
        sha1 = "a58d0df042c186fcf822a8e8015f5450d2d79a8b";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 = "27HBghJxjiZtIk3Ycvn/4kbJk/1uZuJFfuPEns6LaEvpvG1f0hTea8lilrouyo9mVc2GWdcEZ8OLoGmSADlrCw==";
      };
    };
    "concat-stream-2.0.0" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-2.0.0.tgz";
        sha512 = "MWufYdFw53ccGjCA+Ol7XJYpAlW6/prSMzuPOTRnJGcGzuhLn4Scrz7qf6o8bROZ514ltazcIFJZevcfbo0x7A==";
      };
    };
    "console-browserify-1.2.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.2.0.tgz";
        sha512 = "ZMkYO/LkF17QvCPqM0gxw8yUzigAOZOSWSHg91FH6orS7vcEj5dVZTidN2fQ14yBSdg97RqhSNwLUXInd52OTA==";
      };
    };
    "constants-browserify-1.0.0" = {
      name = "constants-browserify";
      packageName = "constants-browserify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/constants-browserify/-/constants-browserify-1.0.0.tgz";
        sha1 = "c20b96d8c617748aaf1c16021760cd27fcb8cb75";
      };
    };
    "convert-source-map-1.1.3" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.1.3.tgz";
        sha1 = "4829c877e9fe49b3161f3bf3673888e204699860";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "create-ecdh-4.0.3" = {
      name = "create-ecdh";
      packageName = "create-ecdh";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-ecdh/-/create-ecdh-4.0.3.tgz";
        sha512 = "GbEHQPMOswGpKXM9kCWVrremUcBmjteUaQ01T9rkKCPDXfUHX0IoP9LpHYo2NPFampa4e+/pFDc3jQdxrxQLaw==";
      };
    };
    "create-hash-1.2.0" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.2.0.tgz";
        sha512 = "z00bCGNHDG8mHAkP7CtT1qVu+bFQUPjYq/4Iv3C3kWjTFV10zIjfSoeqXo9Asws8gwSHDGj/hl2u4OGIjapeCg==";
      };
    };
    "create-hmac-1.1.7" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.7.tgz";
        sha512 = "MJG9liiZ+ogc4TzUwuvbER1JRdgvUFSB5+VR/g5h82fGaIRWMWddtKBHi7/sVhfjQZ6SehlyhvQYrcYkaUIpLg==";
      };
    };
    "crypto-browserify-3.12.0" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "3.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-3.12.0.tgz";
        sha512 = "fz4spIh+znjO2VjL+IdhEpRJ3YN6sMzITSBijk6FK2UvTqruSQW+/cCZTSNsMiZNvUeq0CqurF+dAbyiGOY6Wg==";
      };
    };
    "dash-ast-1.0.0" = {
      name = "dash-ast";
      packageName = "dash-ast";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dash-ast/-/dash-ast-1.0.0.tgz";
        sha512 = "Vy4dx7gquTeMcQR/hDkYLGUnwVil6vk4FOOct+djUnHOUWt+zJPJAaRIXaAFkPXtJjvlY7o3rfRu0/3hpnwoUA==";
      };
    };
    "defined-1.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz";
        sha1 = "c98d9bcef75674188e110969151199e39b1fa693";
      };
    };
    "deps-sort-2.0.1" = {
      name = "deps-sort";
      packageName = "deps-sort";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deps-sort/-/deps-sort-2.0.1.tgz";
        sha512 = "1orqXQr5po+3KI6kQb9A4jnXT1PBwggGl2d7Sq2xsnOeI9GPcE/tGcF9UiSZtZBM7MukY4cAh7MemS6tZYipfw==";
      };
    };
    "des.js-1.0.1" = {
      name = "des.js";
      packageName = "des.js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/des.js/-/des.js-1.0.1.tgz";
        sha512 = "Q0I4pfFrv2VPd34/vfLrFOoRmlYj3OV50i7fskps1jZWK1kApMWWT9G6RRUeYedLcBDIhnSDaUvJMb3AhUlaEA==";
      };
    };
    "detective-5.2.0" = {
      name = "detective";
      packageName = "detective";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detective/-/detective-5.2.0.tgz";
        sha512 = "6SsIx+nUUbuK0EthKjv0zrdnajCCXVYGmbYYiYjFVpzcjwEs/JMDZ8tPRG29J/HhN56t3GJp2cGSWDRjjot8Pg==";
      };
    };
    "diffie-hellman-5.0.3" = {
      name = "diffie-hellman";
      packageName = "diffie-hellman";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-5.0.3.tgz";
        sha512 = "kqag/Nl+f3GwyK25fhUMYj81BUOrZ9IuJsjIcDE5icNM9FJHAVm3VcUDxdLPoQtTuUylWm6ZIknYJwwaPxsUzg==";
      };
    };
    "domain-browser-1.2.0" = {
      name = "domain-browser";
      packageName = "domain-browser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domain-browser/-/domain-browser-1.2.0.tgz";
        sha512 = "jnjyiM6eRyZl2H+W8Q/zLMA481hzi0eszAaBUzIVnmYVDBbnLxVNnfu1HgEBvCbL+71FrxMl3E6lpKH7Ge3OXA==";
      };
    };
    "duplexer2-0.1.4" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.1.4.tgz";
        sha1 = "8b12dab878c0d69e3e7891051662a32fc6bddcc1";
      };
    };
    "elliptic-6.5.3" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.5.3.tgz";
        sha512 = "IMqzv5wNQf+E6aHeIqATs0tOLeOTwj1QKbRcS3jBbYkl5oLAserA8yJTT7/VyHUYG91PRmPyeQDObKLPpeS4dw==";
      };
    };
    "es6-promise-3.3.1" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-3.3.1.tgz";
        sha1 = "a08cdde84ccdbf34d027a1451bc91d4bcd28a613";
      };
    };
    "events-2.1.0" = {
      name = "events";
      packageName = "events";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-2.1.0.tgz";
        sha512 = "3Zmiobend8P9DjmKAty0Era4jV8oJ0yGYe2nJJAxgymF9+N8F2m0hhZiMoWtcfepExzNKZumFU3ksdQbInGWCg==";
      };
    };
    "evp_bytestokey-1.0.3" = {
      name = "evp_bytestokey";
      packageName = "evp_bytestokey";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/evp_bytestokey/-/evp_bytestokey-1.0.3.tgz";
        sha512 = "/f2Go4TognH/KvCISP7OUsHn85hT9nUkxxA9BEWxFn+Oj9o8ZNLm/40hdlgSLyuOimsrTKLUMEorQexp/aPQeA==";
      };
    };
    "fast-safe-stringify-2.0.7" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.0.7.tgz";
        sha512 = "Utm6CdzT+6xsDk2m8S6uL8VHxNwI6Jub+e9NYTcAms28T84pTa25GJQV9j0CY0N1rM8hK4x6grpF2BQf+2qwVA==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "gaze-1.1.3" = {
      name = "gaze";
      packageName = "gaze";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/gaze/-/gaze-1.1.3.tgz";
        sha512 = "BRdNm8hbWzFzWHERTrejLqwHDfS4GibPoq5wjTPIoJHoBtKGPg3xAFfxmM+9ztbXelxcf2hwQcaz1PtmFeue8g==";
      };
    };
    "get-assigned-identifiers-1.2.0" = {
      name = "get-assigned-identifiers";
      packageName = "get-assigned-identifiers";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-assigned-identifiers/-/get-assigned-identifiers-1.2.0.tgz";
        sha512 = "mBBwmeGTrxEMO4pMaaf/uUEFHnYtwr8FTe8Y/mer4rcV/bye0qGm6pw1bGZFGStxC5O76c5ZAVBGnqHmOaJpdQ==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "globule-1.3.2" = {
      name = "globule";
      packageName = "globule";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/globule/-/globule-1.3.2.tgz";
        sha512 = "7IDTQTIu2xzXkT+6mlluidnWo+BypnbSoEVVQCGfzqnl5Ik8d3e1d4wycb8Rj9tWW+Z39uPWsdlquqiqPCd/pA==";
      };
    };
    "graceful-fs-4.2.4" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.4.tgz";
        sha512 = "WjKPNJF79dtJAVniUlGGWHYGz2jWxT6VhN/4m1NdkbZ2nOsEF+cI1Edgql5zCRhs/VsQYRvrXctxktVXZUkixw==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "hash-base-3.1.0" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.1.0.tgz";
        sha512 = "1nmYp/rhMDiE7AYkDw+lLwlAzz0AntGIe51F3RfFfEqyQ3feY2eI/NcwC6umIQVOASPMsWJLJScWKSSvzL9IVA==";
      };
    };
    "hash.js-1.1.7" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.1.7.tgz";
        sha512 = "taOaskGt4z4SOANNseOviYDvjEJinIkRgmp7LbKP2YTTmVxWBl87s/uzK9r+44BclBSp2X7K1hqeNfz9JbBeXA==";
      };
    };
    "hmac-drbg-1.0.1" = {
      name = "hmac-drbg";
      packageName = "hmac-drbg";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hmac-drbg/-/hmac-drbg-1.0.1.tgz";
        sha1 = "d2745701025a6c775a6c545793ed502fc0c649a1";
      };
    };
    "htmlescape-1.1.1" = {
      name = "htmlescape";
      packageName = "htmlescape";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.1.tgz";
        sha1 = "3a03edc2214bca3b66424a3e7959349509cb0351";
      };
    };
    "https-browserify-1.0.0" = {
      name = "https-browserify";
      packageName = "https-browserify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-browserify/-/https-browserify-1.0.0.tgz";
        sha1 = "ec06c10e0a34c0f2faf199f7fd7fc78fffd03c73";
      };
    };
    "ieee754-1.1.13" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.13.tgz";
        sha512 = "4vf7I2LYV/HaWerSo3XmlMkp5eZ83i+/CDluXi/IGTs/O1sejBNhTtnxzmRZfvOUqj7lZjqHkeTvpgSFDlWZTg==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "inline-source-map-0.6.2" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.6.2.tgz";
        sha1 = "f9393471c18a79d1724f863fa38b586370ade2a5";
      };
    };
    "insert-module-globals-7.2.0" = {
      name = "insert-module-globals";
      packageName = "insert-module-globals";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-7.2.0.tgz";
        sha512 = "VE6NlW+WGn2/AeOMd496AHFYmE7eLKkUY6Ty31k4og5vmA3Fjuwe9v6ifH6Xx/Hz27QvdoMoviw1/pqWRB09Sw==";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "json-stable-stringify-0.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-0.0.1.tgz";
        sha1 = "611c23e814db375527df851193db59dd2af27f45";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "jsonparse-0.0.5" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-0.0.5.tgz";
        sha1 = "330542ad3f0a654665b778f3eb2d9a9fa507ac64";
      };
    };
    "jsonparse-1.3.1" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.1.tgz";
        sha1 = "3f4dae4a91fac315f71062f8521cc239f1366280";
      };
    };
    "labeled-stream-splicer-2.0.2" = {
      name = "labeled-stream-splicer";
      packageName = "labeled-stream-splicer";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/labeled-stream-splicer/-/labeled-stream-splicer-2.0.2.tgz";
        sha512 = "Ca4LSXFFZUjPScRaqOcFxneA0VpKZr4MMYCljyQr4LIewTLb3Y0IUTIsnBBsVubIeEfxeSZpSjSsRM8APEQaAw==";
      };
    };
    "lodash-4.17.19" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.19.tgz";
        sha512 = "JNvd8XER9GQX0v2qJgsaN/mzFCNA5BRe/j8JN9d+tWyGLSodKQHKFicdwNYzWwI3wjRnaKPsGj1XkBjx/F96DQ==";
      };
    };
    "lodash.memoize-3.0.4" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz";
        sha1 = "2dcbd2c287cbc0a55cc42328bd0c736150d53e3f";
      };
    };
    "md5.js-1.3.5" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.5.tgz";
        sha512 = "xitP+WxNPcTTOgnTJcrhM0xvdPepipPSf3I8EIpGKeFLjt3PlJLIDG3u8EX53ZIubkb+5U2+3rELYpEhHhzdkg==";
      };
    };
    "miller-rabin-4.0.1" = {
      name = "miller-rabin";
      packageName = "miller-rabin";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/miller-rabin/-/miller-rabin-4.0.1.tgz";
        sha512 = "115fLhvZVqWwHPbClyntxEVfVDfl9DLLTuJvq3g2O/Oxi8AiNouAHvDSzHS0viUJc+V5vm3eq91Xwqn9dp4jRA==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "minimalistic-assert-1.0.1" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz";
        sha512 = "UtJcAD4yEaGtjPezWuO9wC4nwUnVH/8/Im3yEHQP4b67cXlD/Qr9hdITCU1xDbSEXg2XKNaP8jsReV7vQd00/A==";
      };
    };
    "minimalistic-crypto-utils-1.0.1" = {
      name = "minimalistic-crypto-utils";
      packageName = "minimalistic-crypto-utils";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz";
        sha1 = "f6c00c1c0b082246e5c4d99dfb8c7c083b2b582a";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha1 = "de3f98543dbf96082be48ad1a0c7cda836301dcf";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "mkdirp-0.5.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.5.tgz";
        sha512 = "NKmAlESf6jMGym1++R0Ra7wvhV+wFW63FaSOFPwRahvea0gMUcGUhVeAg/0BC0wiv9ih5NYPB1Wn1UEI1/L+xQ==";
      };
    };
    "mkdirp-classic-0.5.3" = {
      name = "mkdirp-classic";
      packageName = "mkdirp-classic";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp-classic/-/mkdirp-classic-0.5.3.tgz";
        sha512 = "gKLcREMhtuZRwRAfqP3RFW+TK4JqApVBtOIftVgjuABpAtpxhPGaDcfvbhNvD0B8iD1oUr/txX35NjcaY6Ns/A==";
      };
    };
    "module-deps-6.2.2" = {
      name = "module-deps";
      packageName = "module-deps";
      version = "6.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-deps/-/module-deps-6.2.2.tgz";
        sha512 = "a9y6yDv5u5I4A+IPHTnqFxcaKr4p50/zxTjcQJaX2ws9tN/W6J6YXnEKhqRyPhl494dkcxx951onSKVezmI+3w==";
      };
    };
    "mold-source-map-0.4.0" = {
      name = "mold-source-map";
      packageName = "mold-source-map";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mold-source-map/-/mold-source-map-0.4.0.tgz";
        sha1 = "cf67e0b31c47ab9badb5c9c25651862127bb8317";
      };
    };
    "mute-stream-0.0.8" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.8.tgz";
        sha512 = "nnbWWOkoWyUsTjKrhgD0dcz22mdkSnpYqbEjIm2nhwhuxlSkpywJmBo8h0ZqJdkp73mb90SssHkN4rsRaBAfAA==";
      };
    };
    "node-static-0.7.11" = {
      name = "node-static";
      packageName = "node-static";
      version = "0.7.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-static/-/node-static-0.7.11.tgz";
        sha512 = "zfWC/gICcqb74D9ndyvxZWaI1jzcoHmf4UTHWQchBNuNMxdBLJMDiUgZ1tjGLEIe/BMhj2DxKD8HOuc2062pDQ==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "os-browserify-0.3.0" = {
      name = "os-browserify";
      packageName = "os-browserify";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-browserify/-/os-browserify-0.3.0.tgz";
        sha1 = "854373c7f5c2315914fc9bfc6bd8238fdda1ec27";
      };
    };
    "pako-1.0.11" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.11.tgz";
        sha512 = "4hLB8Py4zZce5s4yd9XzopqwVv/yGNhV1Bl8NTmCq1763HeK2+EwVTv+leGeL13Dnh2wfbqowVPXCIO0z4taYw==";
      };
    };
    "parents-1.0.1" = {
      name = "parents";
      packageName = "parents";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parents/-/parents-1.0.1.tgz";
        sha1 = "fedd4d2bf193a77745fe71e371d73c3307d9c751";
      };
    };
    "parse-asn1-5.1.5" = {
      name = "parse-asn1";
      packageName = "parse-asn1";
      version = "5.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-asn1/-/parse-asn1-5.1.5.tgz";
        sha512 = "jkMYn1dcJqF6d5CpU689bq7w/b5ALS9ROVSpQDPrZsqqesUJii9qutvoT5ltGedNXMO2e16YUWIghG9KxaViTQ==";
      };
    };
    "path-browserify-0.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.1.tgz";
        sha512 = "BapA40NHICOS+USX9SN4tyhq+A2RrN/Ws5F0Z5aMHDp98Fl86lX8Oti8B7uN93L4Ifv4fHOEA+pQw87gmMO/lQ==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-platform-0.11.15" = {
      name = "path-platform";
      packageName = "path-platform";
      version = "0.11.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-platform/-/path-platform-0.11.15.tgz";
        sha1 = "e864217f74c36850f0852b78dc7bf7d4a5721bf2";
      };
    };
    "pbkdf2-3.1.1" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.1.1.tgz";
        sha512 = "4Ejy1OPxi9f2tt1rRV7Go7zmfDQ+ZectEQz3VGUQhgq62HtIRPDyG/JtnwIxs6x3uNMwo2V7q1fMvKjb+Tnpqg==";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha1 = "7332300e840161bda3e69a1d1d91a7d4bc16f182";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "public-encrypt-4.0.3" = {
      name = "public-encrypt";
      packageName = "public-encrypt";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/public-encrypt/-/public-encrypt-4.0.3.tgz";
        sha512 = "zVpa8oKZSz5bTMTFClc1fQOnyyEzpl5ozpi1B5YcvBrdohMjH2rfsBtyXcuNuwjsDIXmBYlF2N5FlJYhR29t8Q==";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "querystring-es3-0.2.1" = {
      name = "querystring-es3";
      packageName = "querystring-es3";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring-es3/-/querystring-es3-0.2.1.tgz";
        sha1 = "9ec61f79049875707d69414596fd907a4d711e73";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "randomfill-1.0.4" = {
      name = "randomfill";
      packageName = "randomfill";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomfill/-/randomfill-1.0.4.tgz";
        sha512 = "87lcbR8+MhcWcUiQ+9e+Rwx8MyR2P7qnt15ynUlbm3TU/fjbgz4GsvfSUDTemtCCtVCqb4ZcEFlyPNTh9bBTLw==";
      };
    };
    "read-1.0.7" = {
      name = "read";
      packageName = "read";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/read/-/read-1.0.7.tgz";
        sha1 = "b3da19bd052431a97671d44a42634adf710b40c4";
      };
    };
    "read-only-stream-2.0.0" = {
      name = "read-only-stream";
      packageName = "read-only-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-only-stream/-/read-only-stream-2.0.0.tgz";
        sha1 = "2724fd6a8113d73764ac288d4386270c1dbf17f0";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "resolve-1.17.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.17.0.tgz";
        sha512 = "ic+7JYiV8Vi2yzQGFWOkiZD5Z9z7O2Zhm9XMaTxdJExKasieFCr+yXZ/WmXsckHiKl12ar0y6XiXDx3m4RHn1w==";
      };
    };
    "rimraf-2.6.3" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.3.tgz";
        sha512 = "mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA==";
      };
    };
    "rimraf-2.7.1" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz";
        sha512 = "uWjbaKIK3T1OSVptzX7Nl6PvQ3qAGtKEtVRjRuazjfL3Bx5eI409VZSqgND+4UNnmzLVdPj9FqFJNPqBZFve4w==";
      };
    };
    "ripemd160-2.0.2" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.2.tgz";
        sha512 = "ii4iagi25WusVoiC4B4lq7pbXfAp3D9v5CwfkY33vffw2+pkDjY1D8GaN7spsxvCSx8dkPqOZCEZyfxcmJG2IA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "sander-0.5.1" = {
      name = "sander";
      packageName = "sander";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sander/-/sander-0.5.1.tgz";
        sha1 = "741e245e231f07cafb6fdf0f133adfa216a502ad";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "shasum-1.0.2" = {
      name = "shasum";
      packageName = "shasum";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum/-/shasum-1.0.2.tgz";
        sha1 = "e7012310d8f417f4deb5712150e5678b87ae565f";
      };
    };
    "shasum-object-1.0.0" = {
      name = "shasum-object";
      packageName = "shasum-object";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum-object/-/shasum-object-1.0.0.tgz";
        sha512 = "Iqo5rp/3xVi6M4YheapzZhhGPVs0yZwHj7wvwQ1B9z8H6zk+FEnI7y3Teq7qwnekfEhu8WmG2z0z4iWZaxLWVg==";
      };
    };
    "shell-quote-1.7.2" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.7.2.tgz";
        sha512 = "mRz/m/JVscCrkMyPqHc/bczi3OQHkLTqXHEFu0zDhK/qfv3UcOA4SVmRCLmos4bhjr9ekVQubj/R7waKapmiQg==";
      };
    };
    "simple-concat-1.0.1" = {
      name = "simple-concat";
      packageName = "simple-concat";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.1.tgz";
        sha512 = "cSFtAPtRhljv69IK0hTVZQ+OfE9nePi/rtJmw5UjHeVyVroEqJXP1sFztKUy1qU+xvz3u/sfYJLa947b7nAN2Q==";
      };
    };
    "sorcery-0.10.0" = {
      name = "sorcery";
      packageName = "sorcery";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sorcery/-/sorcery-0.10.0.tgz";
        sha1 = "8ae90ad7d7cb05fc59f1ab0c637845d5c15a52b7";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "sourcemap-codec-1.4.8" = {
      name = "sourcemap-codec";
      packageName = "sourcemap-codec";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sourcemap-codec/-/sourcemap-codec-1.4.8.tgz";
        sha512 = "9NykojV5Uih4lgo5So5dtw+f0JgJX30KCNI8gwhz2J9A15wD0Ml6tjHKwf6fTSa6fAdVBdZeNOs9eJ71qCk8vA==";
      };
    };
    "stream-browserify-2.0.2" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-browserify/-/stream-browserify-2.0.2.tgz";
        sha512 = "nX6hmklHs/gr2FuxYDltq8fJA1GDlxKQCz8O/IM4atRqBH8OORmBNgfvW5gG10GT/qQ9u0CzIvr2X5Pkt6ntqg==";
      };
    };
    "stream-combiner2-1.1.1" = {
      name = "stream-combiner2";
      packageName = "stream-combiner2";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.1.1.tgz";
        sha1 = "fb4d8a1420ea362764e21ad4780397bebcb41cbe";
      };
    };
    "stream-http-3.1.1" = {
      name = "stream-http";
      packageName = "stream-http";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-http/-/stream-http-3.1.1.tgz";
        sha512 = "S7OqaYu0EkFpgeGFb/NPOoPLxFko7TPqtEeFg5DXPB4v/KETHG0Ln6fRFrNezoelpaDKmycEmmZ81cC9DAwgYg==";
      };
    };
    "stream-splicer-2.0.1" = {
      name = "stream-splicer";
      packageName = "stream-splicer";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-splicer/-/stream-splicer-2.0.1.tgz";
        sha512 = "Xizh4/NPuYSyAXyT7g8IvdJ9HJpxIGL9PjyhtywCZvvP0OPIdqyrr4dMikeuvY8xahpdKEBlBTySe583totajg==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "subarg-1.0.0" = {
      name = "subarg";
      packageName = "subarg";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/subarg/-/subarg-1.0.0.tgz";
        sha1 = "f62cf17581e996b48fc965699f54c06ae268b8d2";
      };
    };
    "syntax-error-1.4.0" = {
      name = "syntax-error";
      packageName = "syntax-error";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/syntax-error/-/syntax-error-1.4.0.tgz";
        sha512 = "YPPlu67mdnHGTup2A8ff7BC2Pjq0e0Yp/IyTFN03zWO0RcK07uLcbi7C2KpGR2FvWbaB0+bfE27a+sBKebSo7w==";
      };
    };
    "temp-0.9.1" = {
      name = "temp";
      packageName = "temp";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/temp/-/temp-0.9.1.tgz";
        sha512 = "WMuOgiua1xb5R56lE0eH6ivpVmg/lq2OHm4+LtT/xtEtPQ+sz6N3bBM6WZ5FvO1lO4IKIOb43qnhoc4qxP5OeA==";
      };
    };
    "through-2.2.7" = {
      name = "through";
      packageName = "through";
      version = "2.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.2.7.tgz";
        sha1 = "6e8e21200191d4eb6a99f6f010df46aa1c6eb2bd";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "through2-2.0.5" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.5.tgz";
        sha512 = "/mrRod8xqpA+IHSLyGCQ2s8SPHiCDEeQJSep1jqLYeEUClOFG2Qsh+4FU6G9VeqpZnGW/Su8LQGc4YKni5rYSQ==";
      };
    };
    "timers-browserify-1.4.2" = {
      name = "timers-browserify";
      packageName = "timers-browserify";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/timers-browserify/-/timers-browserify-1.4.2.tgz";
        sha1 = "c9c58b575be8407375cb5e2462dacee74359f41d";
      };
    };
    "tree-kill-1.2.2" = {
      name = "tree-kill";
      packageName = "tree-kill";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tree-kill/-/tree-kill-1.2.2.tgz";
        sha512 = "L0Orpi8qGpRG//Nd+H90vFB+3iHnue1zSSGmNOOCh1GLJ7rUKVwV2HvijphGQS2UmhUZewS9VgvxYIdgr+fG1A==";
      };
    };
    "tty-browserify-0.0.1" = {
      name = "tty-browserify";
      packageName = "tty-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tty-browserify/-/tty-browserify-0.0.1.tgz";
        sha512 = "C3TaO7K81YvjCgQH9Q1S3R3P3BtN3RIM8n+OvX4il1K1zgE8ZhI0op7kClgkxtutIE8hQrcrHBXvIheqKUUCxw==";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "umd-3.0.3" = {
      name = "umd";
      packageName = "umd";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/umd/-/umd-3.0.3.tgz";
        sha512 = "4IcGSufhFshvLNcMCV80UnQVlZ5pMOC8mvNPForqwA4+lzYQuetTESLDQkeLmihq8bRcnpbQa48Wb8Lh16/xow==";
      };
    };
    "undeclared-identifiers-1.1.3" = {
      name = "undeclared-identifiers";
      packageName = "undeclared-identifiers";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/undeclared-identifiers/-/undeclared-identifiers-1.1.3.tgz";
        sha512 = "pJOW4nxjlmfwKApE4zvxLScM/njmwj/DiUBv7EabwE4O8kRUy+HIwxQtZLBPll/jx1LJyBcqNfB3/cpv9EZwOw==";
      };
    };
    "url-0.11.0" = {
      name = "url";
      packageName = "url";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.11.0.tgz";
        sha1 = "3838e97cfc60521eb73c525a8e55bfdd9e2e28f1";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "util-0.10.4" = {
      name = "util";
      packageName = "util";
      version = "0.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.4.tgz";
        sha512 = "0Pm9hTQ3se5ll1XihRic3FDIku70C+iHUdT/W926rSgHV5QgXsYbKZN8MSC3tJtSkhuROzvsQjAaFENRXr+19A==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "vm-browserify-1.1.2" = {
      name = "vm-browserify";
      packageName = "vm-browserify";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vm-browserify/-/vm-browserify-1.1.2.tgz";
        sha512 = "2ham8XPWTONajOR0ohOKOHXkm3+gaBmGut3SRuu75xLd/RRaY6vqgh8NBYYk7+RW3u5AtzPQZG8F10LHkl0lAQ==";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
in
{
  "pulp" = nodeEnv.buildNodePackage {
    name = "pulp";
    packageName = "pulp";
    version = "15.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/pulp/-/pulp-15.0.0.tgz";
      sha512 = "JPzDiSjxwySAFOFnpevZO7YzzDgGdJP/SQap1UJbK0rsrfUVQC+zOHDkm7A8T3gR/0el4ft6KwB6fcDl2bTzVw==";
    };
    dependencies = [
      sources."JSONStream-1.3.5"
      sources."acorn-7.3.1"
      sources."acorn-node-1.8.2"
      sources."acorn-walk-7.2.0"
      (sources."asn1.js-4.10.1" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      (sources."assert-1.5.0" // {
        dependencies = [
          sources."inherits-2.0.1"
          sources."util-0.10.3"
        ];
      })
      sources."async-1.5.2"
      sources."balanced-match-1.0.0"
      sources."base64-js-1.3.1"
      sources."bn.js-5.1.2"
      sources."brace-expansion-1.1.11"
      sources."brorand-1.1.0"
      sources."browser-pack-6.1.0"
      (sources."browser-resolve-1.11.3" // {
        dependencies = [
          sources."resolve-1.1.7"
        ];
      })
      (sources."browserify-16.5.1" // {
        dependencies = [
          sources."concat-stream-1.6.2"
        ];
      })
      sources."browserify-aes-1.2.0"
      sources."browserify-cache-api-3.0.1"
      sources."browserify-cipher-1.0.1"
      sources."browserify-des-1.0.2"
      (sources."browserify-incremental-3.1.1" // {
        dependencies = [
          sources."JSONStream-0.10.0"
          sources."jsonparse-0.0.5"
        ];
      })
      (sources."browserify-rsa-4.0.1" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      (sources."browserify-sign-4.2.0" // {
        dependencies = [
          sources."readable-stream-3.6.0"
        ];
      })
      sources."browserify-zlib-0.2.0"
      sources."buffer-5.2.1"
      sources."buffer-crc32-0.2.13"
      sources."buffer-from-1.1.1"
      sources."buffer-xor-1.0.3"
      sources."builtin-status-codes-3.0.0"
      sources."cached-path-relative-1.0.2"
      sources."cipher-base-1.0.4"
      sources."colors-1.4.0"
      sources."combine-source-map-0.8.0"
      sources."concat-map-0.0.1"
      (sources."concat-stream-2.0.0" // {
        dependencies = [
          sources."readable-stream-3.6.0"
        ];
      })
      sources."console-browserify-1.2.0"
      sources."constants-browserify-1.0.0"
      sources."convert-source-map-1.1.3"
      sources."core-util-is-1.0.2"
      (sources."create-ecdh-4.0.3" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."create-hash-1.2.0"
      sources."create-hmac-1.1.7"
      sources."crypto-browserify-3.12.0"
      sources."dash-ast-1.0.0"
      sources."defined-1.0.0"
      sources."deps-sort-2.0.1"
      sources."des.js-1.0.1"
      sources."detective-5.2.0"
      (sources."diffie-hellman-5.0.3" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."domain-browser-1.2.0"
      sources."duplexer2-0.1.4"
      (sources."elliptic-6.5.3" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."es6-promise-3.3.1"
      sources."events-2.1.0"
      sources."evp_bytestokey-1.0.3"
      sources."fast-safe-stringify-2.0.7"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."gaze-1.1.3"
      sources."get-assigned-identifiers-1.2.0"
      sources."glob-7.1.6"
      sources."globule-1.3.2"
      sources."graceful-fs-4.2.4"
      sources."has-1.0.3"
      (sources."hash-base-3.1.0" // {
        dependencies = [
          sources."readable-stream-3.6.0"
        ];
      })
      sources."hash.js-1.1.7"
      sources."hmac-drbg-1.0.1"
      sources."htmlescape-1.1.1"
      sources."https-browserify-1.0.0"
      sources."ieee754-1.1.13"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."inline-source-map-0.6.2"
      (sources."insert-module-globals-7.2.0" // {
        dependencies = [
          sources."concat-stream-1.6.2"
        ];
      })
      sources."is-buffer-1.1.6"
      sources."isarray-1.0.0"
      sources."isexe-2.0.0"
      sources."json-stable-stringify-0.0.1"
      sources."jsonify-0.0.0"
      sources."jsonparse-1.3.1"
      sources."labeled-stream-splicer-2.0.2"
      sources."lodash-4.17.19"
      sources."lodash.memoize-3.0.4"
      sources."md5.js-1.3.5"
      (sources."miller-rabin-4.0.1" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."mime-1.6.0"
      sources."minimalistic-assert-1.0.1"
      sources."minimalistic-crypto-utils-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.5"
      sources."mkdirp-0.5.5"
      sources."mkdirp-classic-0.5.3"
      (sources."module-deps-6.2.2" // {
        dependencies = [
          sources."concat-stream-1.6.2"
        ];
      })
      (sources."mold-source-map-0.4.0" // {
        dependencies = [
          sources."through-2.2.7"
        ];
      })
      sources."mute-stream-0.0.8"
      sources."node-static-0.7.11"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      (sources."optimist-0.6.1" // {
        dependencies = [
          sources."minimist-0.0.10"
          sources."wordwrap-0.0.3"
        ];
      })
      sources."os-browserify-0.3.0"
      sources."pako-1.0.11"
      sources."parents-1.0.1"
      sources."parse-asn1-5.1.5"
      sources."path-browserify-0.0.1"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      sources."path-platform-0.11.15"
      sources."pbkdf2-3.1.1"
      sources."process-0.11.10"
      sources."process-nextick-args-2.0.1"
      (sources."public-encrypt-4.0.3" // {
        dependencies = [
          sources."bn.js-4.11.9"
        ];
      })
      sources."punycode-1.4.1"
      sources."querystring-0.2.0"
      sources."querystring-es3-0.2.1"
      sources."randombytes-2.1.0"
      sources."randomfill-1.0.4"
      sources."read-1.0.7"
      sources."read-only-stream-2.0.0"
      (sources."readable-stream-2.3.7" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."resolve-1.17.0"
      sources."rimraf-2.7.1"
      sources."ripemd160-2.0.2"
      sources."safe-buffer-5.2.1"
      sources."sander-0.5.1"
      sources."sha.js-2.4.11"
      sources."shasum-1.0.2"
      sources."shasum-object-1.0.0"
      sources."shell-quote-1.7.2"
      sources."simple-concat-1.0.1"
      sources."sorcery-0.10.0"
      sources."source-map-0.5.7"
      sources."sourcemap-codec-1.4.8"
      sources."stream-browserify-2.0.2"
      sources."stream-combiner2-1.1.1"
      (sources."stream-http-3.1.1" // {
        dependencies = [
          sources."readable-stream-3.6.0"
        ];
      })
      sources."stream-splicer-2.0.1"
      sources."string_decoder-1.3.0"
      sources."subarg-1.0.0"
      sources."syntax-error-1.4.0"
      (sources."temp-0.9.1" // {
        dependencies = [
          sources."rimraf-2.6.3"
        ];
      })
      sources."through-2.3.8"
      sources."through2-2.0.5"
      sources."timers-browserify-1.4.2"
      sources."tree-kill-1.2.2"
      sources."tty-browserify-0.0.1"
      sources."typedarray-0.0.6"
      sources."umd-3.0.3"
      sources."undeclared-identifiers-1.1.3"
      (sources."url-0.11.0" // {
        dependencies = [
          sources."punycode-1.3.2"
        ];
      })
      (sources."util-0.10.4" // {
        dependencies = [
          sources."inherits-2.0.3"
        ];
      })
      sources."util-deprecate-1.0.2"
      sources."vm-browserify-1.1.2"
      sources."which-1.3.1"
      sources."wordwrap-1.0.0"
      sources."wrappy-1.0.2"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A build system for PureScript projects";
      homepage = https://github.com/purescript-contrib/pulp;
      license = "LGPL-3.0+";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
