# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  purs-tidy = nodeEnv.buildNodePackage {
    name = "purs-tidy";
    packageName = "purs-tidy";
    version = "0.10.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/purs-tidy/-/purs-tidy-0.10.0.tgz";
      sha512 = "ULbJfBHRngczYwcOzugytRiNy+Guy2VXoAG1jMtGaSFEaUZk1lZkKU11t8jIZTrDdOrkgqlWCZLi3mfcHvdimA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A syntax tidy-upper (formatter) for PureScript.";
      homepage = "https://github.com/natefaubion/purescript-tidy#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
