# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "purs-backend-es-1.1.0" = {
      name = "purs-backend-es";
      packageName = "purs-backend-es";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/purs-backend-es/-/purs-backend-es-1.1.0.tgz";
        sha512 = "AC7OLAAmGyslvNriOOE6BaEDoG3UKsT2Pw2P72R2DLhn7yiAsRNH60/1e+Huj29Vyn2ClWaY7TEQAu7AFclqGQ==";
      };
    };
  };
  args = {
    name = "purs-backend-es";
    packageName = "purs-backend-es";
    version = "v1.1.0";
    src = ./.;
    dependencies = [
      sources."purs-backend-es-1.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
