# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha512 = "TIGnTpdo+E3+pCyAluZvtED5p5wCqLdezCyhPZzKPcxvFplEt4i+W7OONCKgeZFT3+y5NZZfOOS/Bdcanm1MYA==";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha512 = "kmCevFghRiWM7HB5zTPULl4r9bVFSWjz62MhqizDGUrq2NWuNMQyuv4tHHoKJHs69M/MF64lEcHdYIocrdWQYA==";
      };
    };
    "ansicolors-0.2.1" = {
      name = "ansicolors";
      packageName = "ansicolors";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansicolors/-/ansicolors-0.2.1.tgz";
        sha512 = "tOIuy1/SK/dr94ZA0ckDohKXNeBNqZ4us6PjMVLs5h1w2GBB6uPtOknp2+VF4F/zcy9LI70W+Z+pE2Soajky1w==";
      };
    };
    "cardinal-1.0.0" = {
      name = "cardinal";
      packageName = "cardinal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cardinal/-/cardinal-1.0.0.tgz";
        sha512 = "INsuF4GyiFLk8C91FPokbKTc/rwHqV4JnfatVZ6GPhguP1qmkRWX2dp5tepYboYdPpGWisLVLI+KsXoXFPRSMg==";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha512 = "U3lRVLMSlsCfjqYPbLyVv11M9CPW4I728d6TCKMAOJueEeB9/8o+eSsMnxPJD+Q+K909sdESg7C+tIkoH6on1A==";
      };
    };
    "cli-table-0.3.11" = {
      name = "cli-table";
      packageName = "cli-table";
      version = "0.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-table/-/cli-table-0.3.11.tgz";
        sha512 = "IqLQi4lO0nIB4tcdTpN4LCB9FI3uqrJZK7RC515EnhZ6qBaglkIgICb1wjeAqpdoOabm1+SuQtkXIPdYC93jhQ==";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha512 = "pFGrxThWcWQ2MsAz6RtgeWe4NK2kUE1WfsrvvlctdII745EW9I0yflqhe7++M5LEc7bV2c/9/5zc8sFcpL0Drw==";
      };
    };
    "configstore-3.1.5" = {
      name = "configstore";
      packageName = "configstore";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/configstore/-/configstore-3.1.5.tgz";
        sha512 = "nlOhI4+fdzoK5xmJ+NY+1gZK56bwEaWZr8fYuXohZ9Vkc1o3a4T/R3M+yE/w7x/ZVJ1zF8c+oaOvF0dztdUgmA==";
      };
    };
    "crypto-random-string-1.0.0" = {
      name = "crypto-random-string";
      packageName = "crypto-random-string";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-random-string/-/crypto-random-string-1.0.0.tgz";
        sha512 = "GsVpkFPlycH7/fRR7Dhcmnoii54gV1nz7y4CWyeFS14N+JVBBhY+r8amRHE4BwSYal7BPTDp8isvAlCxyFt3Hg==";
      };
    };
    "dot-prop-4.2.1" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-4.2.1.tgz";
        sha512 = "l0p4+mIuJIua0mhxGoh4a+iNL9bmeK5DvnSVQa6T0OhrVmaEa1XScX5Etc673FePCJOArq/4Pa2cLGODUWTPOQ==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "esprima-3.0.0" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.0.0.tgz";
        sha512 = "xoBq/MIShSydNZOkjkoCEjqod963yHNXTLC40ypBhop6yPqflPz/vTinmCfSrGcywVLnSftRf6a0kJLdFdzemw==";
      };
    };
    "figlet-1.6.0" = {
      name = "figlet";
      packageName = "figlet";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figlet/-/figlet-1.6.0.tgz";
        sha512 = "31EQGhCEITv6+hi2ORRPyn3bulaV9Fl4xOdR169cBzH/n1UqcxsiSB/noo6SJdD7Kfb1Ljit+IgR1USvF/XbdA==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha512 = "C8vBJ8DwUCx19vhm7urhTuUsr4/IyP6l4VzNQDv+ryHQObW3TTTp9yB68WpYgRe2bbaGuZ/se74IqFeVnMnLZg==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha512 = "JmXMZ6wuvDmLiHEml9ykzqO6lwFbof0GG4IkcGaENdCRDDmMVnny7s5HsIgHCbaq0w2MyPhDqkhTUgS2LU2PHA==";
      };
    };
    "is-obj-1.0.1" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-1.0.1.tgz";
        sha512 = "l4RyHgRqGN4Y3+9JHVrNqO+tN0rV5My76uW5/nuO4K1b6vw5G8d/cmFjP9tRfEsdhZNt0IFdZuK/c2Vr4Nb+Qg==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash.assign-4.2.0" = {
      name = "lodash.assign";
      packageName = "lodash.assign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assign/-/lodash.assign-4.2.0.tgz";
        sha512 = "hFuH8TY+Yji7Eja3mGiuAxBqLagejScbG8GbG0j6o9vzn0YL14My+ktnqtZgFTosKymC9/44wP6s7xyuLfnClw==";
      };
    };
    "make-dir-1.3.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-1.3.0.tgz";
        sha512 = "2w31R7SJtieJJnQtGc7RVL2StM2vGYVfqUOvUDxH6bC6aJTxPxTF0GnIgCyu7tjockiUWAYQRbxa7vKn34s5sQ==";
      };
    };
    "marked-0.3.19" = {
      name = "marked";
      packageName = "marked";
      version = "0.3.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-0.3.19.tgz";
        sha512 = "ea2eGWOqNxPcXv8dyERdSr/6FmzvWwzjMxpfGB/sbMccXoct+xY+YukPD+QTUZwyvK7BZwcr4m21WBOW41pAkg==";
      };
    };
    "marked-terminal-2.0.0" = {
      name = "marked-terminal";
      packageName = "marked-terminal";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked-terminal/-/marked-terminal-2.0.0.tgz";
        sha512 = "aZ7yKAww2yyYsuBbO4NoaD8ExWXKYy9k3rWcWUS9iI1wrYtr6vrVeUHdwoBEElrRpKkb0ZWlJi4K392XBYet4A==";
      };
    };
    "node-emoji-1.11.0" = {
      name = "node-emoji";
      packageName = "node-emoji";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-emoji/-/node-emoji-1.11.0.tgz";
        sha512 = "wo2DpQkQp7Sjm2A0cq+sN7EHKO6Sl0ctXeBdFZrL9T9+UywORbufTcTZxom8YqpLQt/FqNMUkOpkZrJVYSKD3A==";
      };
    };
    "pify-3.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-3.0.0.tgz";
        sha512 = "C3FsVNH1udSEX48gGX1xfvwTWfsYWj5U+8/uK15BGzIGrKoUpghX8hWZwa/OFnakBiiVNmBvemTJR5mcy7iPcg==";
      };
    };
    "redeyed-1.0.1" = {
      name = "redeyed";
      packageName = "redeyed";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redeyed/-/redeyed-1.0.1.tgz";
        sha512 = "8eEWsNCkV2rvwKLS1Cvp5agNjMhwRe2um+y32B2+3LqOzg4C9BBPs6vzAfV16Ivb8B9HPNKIqd8OrdBws8kNlQ==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha512 = "VhumSSbBqDTP8p2ZLKj40UjBCV4+v8bUSEpUb4KjRgWk9pbqGF4REFj6KEagidb2f/M6AzC0EmFyDNGaw9OCzg==";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha512 = "KKNVtd6pCYgPIKU4cp2733HWYCpplQhddZLBUryaAHou723x+FRzQ5Df824Fj+IyyuiQTRoub4SnIFfIcrp70g==";
      };
    };
    "unique-string-1.0.0" = {
      name = "unique-string";
      packageName = "unique-string";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-string/-/unique-string-1.0.0.tgz";
        sha512 = "ODgiYu03y5g76A1I9Gt0/chLCzQjvzDy7DsZGsLOE/1MrF6wriEskSncj1+/C58Xk/kPZDppSctDybCwOSaGAg==";
      };
    };
    "write-file-atomic-2.4.3" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-2.4.3.tgz";
        sha512 = "GaETH5wwsX+GcnzhPgKcKjJ6M2Cq3/iZp1WyY/X1CSqrW+jVNM9Y7D8EC2sM4ZG/V8wZlSniJnCKWPmBYAucRQ==";
      };
    };
    "xdg-basedir-3.0.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-3.0.0.tgz";
        sha512 = "1Dly4xqlulvPD3fZUQJLY+FUIeqN3N2MM3uqe4rCJftAvOjFa3jFGfctOgluGx4ahPbUCsZkmJILiP0Vi4T6lQ==";
      };
    };
  };
in
{
  psa = nodeEnv.buildNodePackage {
    name = "psa";
    packageName = "psa";
    version = "1.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/psa/-/psa-1.0.0.tgz";
      sha512 = "EbYfuB+KQCuQvq7EfDb8BspQtMPTllNTOeUMA96U6BFu+l+IC++oY7NcRf5s48jNfsx/hII+LmJzNwYPPi+H7w==";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."ansicolors-0.2.1"
      sources."cardinal-1.0.0"
      sources."chalk-1.1.3"
      sources."cli-table-0.3.11"
      sources."colors-1.0.3"
      sources."configstore-3.1.5"
      sources."crypto-random-string-1.0.0"
      sources."dot-prop-4.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-3.0.0"
      sources."figlet-1.6.0"
      sources."graceful-fs-4.2.11"
      sources."has-ansi-2.0.0"
      sources."imurmurhash-0.1.4"
      sources."is-obj-1.0.1"
      sources."lodash-4.17.21"
      sources."lodash.assign-4.2.0"
      sources."make-dir-1.3.0"
      sources."marked-0.3.19"
      sources."marked-terminal-2.0.0"
      sources."node-emoji-1.11.0"
      sources."pify-3.0.0"
      sources."redeyed-1.0.1"
      sources."signal-exit-3.0.7"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."unique-string-1.0.0"
      sources."write-file-atomic-2.4.3"
      sources."xdg-basedir-3.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      homepage = "https://github.com/jpnelson/psa#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
