# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  purescript-psa = nodeEnv.buildNodePackage {
    name = "purescript-psa";
    packageName = "purescript-psa";
    version = "0.8.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/purescript-psa/-/purescript-psa-0.8.2.tgz";
      sha512 = "4Olf0aQQrNCfcDLXQI3gJgINEQ+3U+4QPLmQ2LHX2L/YOXSwM7fOGIUs/wMm/FQnwERUyQmHKQTJKB4LIjE2fg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Error/Warning reporting frontend for psc";
      homepage = "https://github.com/natefaubion/purescript-psa#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
