name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        curl https://nixos.org/nix/install | sh
        . /home/runner/.nix-profile/etc/profile.d/nix.sh
        nix
